name: Deploy Preview with Github secrets as env vars

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:
  # You can set whatever event you want
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "public/**"
  #     - "src/**"
  #     - "package.json"
  #     - "tsconfig.json"
  #     - "vercel.json"
  # pull_request_target:
  #   paths:
  #     - "public/**"
  #     - "src/**"
  #     - "package.json"
  #     - "tsconfig.json"
  #     - "vercel.json"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --build-env REACT_APP_ENV_VAR=${{ secrets.ENV_VAR }} --token=${{ secrets.VERCEL_TOKEN }}
