name: Staging Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --environment=preview --yes --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: PWD
        run: pwd
        
      - name: .vercel folder content
        run: ls -la ./.vercel
        
      - name: .env.preview.local file content
        run: cat ./.vercel/.env.preview.local

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --env REACT_APP_ENV_VAR=${{ secrets.ENV_VAR }} --token=${{ secrets.VERCEL_TOKEN }}
